# 当特定文件夹下的文件发生变更、提交 tag 时，
# 1. 打包存在变更的特定文件夹，当前是 src/Administration/Resources/public.tar.gz

name: 'Packages Release'

on:
  push:
    branches:
      - 'trunk'
    tags:
      - "v*.*.*"
    paths:
      - src/Administration/**/*

env:
  # 1. for Github split
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  jobs-split: 
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false
      matrix:
        package:
          -
            local_path: 'Administration'
            split_repository: 'administration'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Administration 
        run: |
          cd src/Administration/Resources
          mkdir -p public/static
          echo ${{ github.sha }} > public/static/Release.txt
          pwd 

      - name: Test Administration
        run: |
          ls -lht src/Administration/Resources/public 

      - name: Get Current Branch 
        id: current_branch 
        run: |
          TAG_NAME=`echo $GITHUB_REF | cut -d / -f3`
          echo $TAG_NAME
          echo "{tag_name}={$TAG_NAME}" >> $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT 
          echo ${{github.event.head_commit.message}}

      - name: Push To Another New Repository
        run: |
          git clone https://github.com/liuzel01/administration.git /tmp/monorepo_split/clone_directory 
          git checkout trunk 
          \cp -r src/Administration/* /tmp/monorepo_split/clone_directory/
          cd /tmp/monorepo_split/clone_directory
          cat << CONF >> .git/config 
          [user]
              name = liuzel01
              email = liuzelin01@gmail.com
          CONF
          cat .git/config
          git add -A .
          git commit -m "${{github.event.head_commit.message}}"
          git config --list 
        # git push origin trunk 
        # cd /github/workspace 
        # ls -lht 

      # - name: Archive directory
      #   run: |
      #     tar -czvpf public.tar.gz ./public
      #   working-directory: 'src/Administration/Resources'

      # - name: Upload Artifact 
      #   uses: actions/upload-artifact@v4.3.1
      #   with:
      #     name: my-artifact
      #     path: src/Administration/Resources/public
          
      # - name: Download artifact 
      #   uses: actions/download-artifact@v4.1.4
      #   with:
      #     name: my-artifact 
      #     path: src/Administration/Resources/public 
      # - run: |
      #     ls -lht  src/Administration/Resources/public

      # 主仓库不需要发布 release
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   if: "startsWith(github.ref, 'refs/tags/')"
      #   with:
      #     files: src/Administration/Resources/public.tar.gz 

      # - name: Get Branch ENV 
      #   run: |
      #     echo $GITHUB_REF



      # # no tag
      # - name: Split Monorepo Without Tag 
      #   if: "!startsWith(github.ref, 'refs/tags/')"
      #   uses: "danharrin/monorepo-split-github-action@v2.3.0"
      #   with:
      #     # package_directory: 'src/${{ matrix.package.local_path }}'
      #     package_directory: 'src/Administration'
      #     repository_organization: 'liuzel01'
      #     repository_name: '${{ matrix.package.split_repository }}'
      #     # branch: '${{ github.ref_name }}'
      #     branch: 'trunk'
      #     user_name: "liuzel01"
      #     user_email: "liuzelin01@gmail.com"

      # # with tag
      # - name: Split Monorepo With Tag
      #   if: "startsWith(github.ref, 'refs/tags/')"
      #   uses: "danharrin/monorepo-split-github-action@v2.3.0"
      #   with:
      #     tag: ${GITHUB_REF#refs/tags/}
      #     # ↓ split "packages/easy-coding-standard" directory
      #     package_directory: 'src/Administration'
      #     # ↓ into https://github.com/symplify/easy-coding-standard repository
      #     repository_organization: 'liuzel01'
      #     repository_name: '${{ matrix.package.split_repository }}'
      #     branch: 'trunk'
      #     # ↓ the user signed under the split commit
      #     user_name: "liuzel01"
      #     user_email: "liuzelin01@gmail.com"